kubectl create secret generic app-credentials --from-literal=quarkus.elasticsearch.password= \
       --from-literal=minio.access-key= \
       --from-literal=minio.secret-key= \
       --from-literal=quarkus.langchain4j.openai.api-key=