apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "OpenShift GitOps"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-gitops-operator